Updated style.css with code
wasn't able to resync into github, not sure why..
message said:

 michelle-portfolio git:(feature-about) git push -u origin feature-about
To github.com:ellescarps/michelle-portfolio.git
 ! [rejected]        feature-about -> feature-about (fetch first)
error: failed to push some refs to 'github.com:ellescarps/michelle-portfolio.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.